### PR TITLE
Config and ModMenu support

### PR DESCRIPTION
**Pull request by spjoes**
Config Support (TinyConfig):
     - Extra Pixel Offsets (add more offset)
     - Dynamic Offset (dynamiclly offset chat depending if armor is equipted)
     - Disable Mod (Disable the mod temporarily)

ModMenu support:
     - Added "Client" Badge to indicate this is a client-sided mod

Known Bugs:
     - Chat is no longer dynamically offset by absorption hearts (ill hopefully fix later and update the pull request/make a new pull request

### CODE REVIEW

**Comment by spjoes** [comment]
I fixed Absorption dynamic offset once again. This should now be all ready to go.

**Comment by spjoes** [comment]
this will also add the suggestion in #6

**Comment by EGOIST1372** [comment]
@gnembon any merge action gonna happen? :D

**Comment by spjoes** [comment]
Been over a year lmao. I hope tho

**Comment by gnembon** [comment]
hey, just seen it. 

should have asked before all that work. All that boilerplate for a simple one-liner mod.... Not really.

This should just be in vanilla.

**Comment by spjoes** [comment]
Yes, it should be in vanilla but it's not so why not give people more customization? Idk. I did write this over a year ago and I still use this branch for myself anyways

**Pull request closed without merging**
